### PR TITLE
Handle case where SimpleLazyObject being treated as an Iterable

### PR DESCRIPTION
**Pull request by andreasnuesslein**

### CODE REVIEW

**Comment by andreasnuesslein** [comment]
@hemache I pulled your PR over here. 

`pip install django_elasticsearch_ng` if you're interested. I have to update the docs asap but basically it rids us of a bunch of repetitive typing (like not having to name all `fields`)

**Comment by hemache** [comment]
Thanks, @andreasnuesslein. 

 Is this a new fork of `django-elasticsearch-dsl`?

**Comment by andreasnuesslein** [comment]
@hemache yes it is - it's on pypi as `django-elasticsearch-ng` (although i'm trying to get `django-elasticsearch` right now https://github.com/pypa/pypi-support/issues/251 .

usage is pretty similar to django-elasticsearch-dsl for now. although i already renamed it: `from django_elasticsearch ...` (skip the `_dsl`)

**Comment by hemache** [comment]
Nice! 

I'm also planning to finish the work on Celery signal processor (https://github.com/sabricot/django-elasticsearch-dsl/pull/87) but need some help to write unit tests

**Comment by andreasnuesslein** [comment]
perfect! :+1:  I'm totally open on adding maintainers to this team `https://github.com/django-elasticsearch` as I think the biggest problem with the current/old repo is those two maintainers never having enough time which could totally happen to one person (me) too obviously

**Comment by andreasnuesslein** [comment]
PS: do you know about https://dramatiq.io/ ? I've always been rather frustrated with celery and recently stumbled upon this - don't know how it performs yet though

**Pull request merged**
